# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flexPartyPlayer}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Varga"]
  s.date = %q{2010-01-03}
  s.description = %q{A Flex Frontend to KitNo}
  s.email = %q{github@varga-net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
     "airake.yml",
     "lib/corelib-08.30.2007.swc",
     "lib/flexunit-08.30.2007.swc",
     "lib/fpp.rb",
     "sample.json",
     "script/destroy",
     "script/flex_compile",
     "script/generate",
     "src/FlexPlayer.mxml",
     "src/assets/app_icons/icon_128.png",
     "src/cc/varga/mvc/ApplicationContext.as",
     "src/cc/varga/mvc/commands/playlist/AddItemToPlaylist.as",
     "src/cc/varga/mvc/commands/playlist/LoadPlaylistCommand.as",
     "src/cc/varga/mvc/commands/registry/RegisterCommands.as",
     "src/cc/varga/mvc/commands/registry/RegisterInjections.as",
     "src/cc/varga/mvc/commands/registry/RegisterViews.as",
     "src/cc/varga/mvc/commands/system/Shutdown.as",
     "src/cc/varga/mvc/commands/system/Startup.as",
     "src/cc/varga/mvc/commands/video/AddVideoCommand.as",
     "src/cc/varga/mvc/events/appBar/AppBarEvent.as",
     "src/cc/varga/mvc/events/controllers/ControllersEvent.as",
     "src/cc/varga/mvc/events/player/PlayerEvent.as",
     "src/cc/varga/mvc/events/playlist/PlaylistURLEvent.as",
     "src/cc/varga/mvc/events/playlist/controller/PlaylistControllerEvent.as",
     "src/cc/varga/mvc/events/serveradmin/ServerAdminEvent.as",
     "src/cc/varga/mvc/events/sound/SoundEvent.as",
     "src/cc/varga/mvc/models/player/PlayerModel.as",
     "src/cc/varga/mvc/models/playlist/PlaylistModel.as",
     "src/cc/varga/mvc/models/sound/ISound.as",
     "src/cc/varga/mvc/models/sound/SoundModel.as",
     "src/cc/varga/mvc/models/sound/SoundModelPlayer.as",
     "src/cc/varga/mvc/views/controllers/Controllers.mxml",
     "src/cc/varga/mvc/views/controllers/ControllersMediator.as",
     "src/cc/varga/mvc/views/infoDisplay/InfoDisplay.mxml",
     "src/cc/varga/mvc/views/infoDisplay/InfoDisplayMediator.as",
     "src/cc/varga/mvc/views/player/PlayerItem.mxml",
     "src/cc/varga/mvc/views/player/PlayerWindow.mxml",
     "src/cc/varga/mvc/views/player/PlayerWindowMediator.as",
     "src/cc/varga/mvc/views/playlisturl/PlaylistURL.mxml",
     "src/cc/varga/mvc/views/playlisturl/PlaylistURLMediator.as",
     "src/cc/varga/mvc/views/playlisturl/controller/PlaylistController.mxml",
     "src/cc/varga/mvc/views/playlisturl/controller/PlaylistControllerMediator.as",
     "src/cc/varga/mvc/views/playlisturl/item/PlaylistItem.mxml",
     "src/cc/varga/mvc/views/playlisturl/item/PlaylistItemMediator.as",
     "src/cc/varga/mvc/views/playlisturl/list/Playlist.mxml",
     "src/cc/varga/mvc/views/playlisturl/list/PlaylistMediator.as",
     "src/cc/varga/mvc/views/playlisturl/list/PlaylistStates.as",
     "src/cc/varga/mvc/views/server/administration/ServerAdmin.mxml",
     "src/cc/varga/mvc/views/server/administration/ServerAdminMediator.as",
     "src/cc/varga/mvc/views/visualisation/Visualisation.mxml",
     "src/cc/varga/mvc/views/visualisation/VisualisationMediator.as",
     "src/cc/varga/utils/FileChecker.as",
     "src/cc/varga/utils/URLHelper.as",
     "src/cc/varga/utils/logging/Logger.as",
     "src/com/automatastudios/audio/audiodecoder/AudioDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/AudioInfo.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/IDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/OggVorbisDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/WAVDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/events/AudioDecoderEvent.as",
     "src/com/automatastudios/data/riff/RIFFChunkInfo.as",
     "src/com/automatastudios/data/riff/RIFFParser.as",
     "src/libs/appinf/appinf.json",
     "src/libs/appinf/config.json",
     "src/libs/appinf/sample.json",
     "src/libs/appinf/server.json",
     "test/Test-app.xml",
     "test/Test.mxml"
  ]
  s.homepage = %q{http://github.com/FrancisVarga/flexPartyPlayer/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Flex Frontend to KitNo}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<airake>, [">= 0"])
    else
      s.add_dependency(%q<airake>, [">= 0"])
    end
  else
    s.add_dependency(%q<airake>, [">= 0"])
  end
end

