gem "jeweler"
gem "sinatra"
gem "rake"
gem "airake", :git => "git://github.com/lennart/airake.git"
gem "emk-sinatra-url-for", :require_as => "sinatra/url_for" 
gem "sinatra-static-assets", :require_as => "sinatra/static_assets", :git => "git://github.com/lennart/sinatra-static-assets"
