gem "jeweler"
gem "sinatra"
gem "sprout"
#gem "rake"
#gem "emk-sinatra-url-for", :require_as => "sinatra/url_for" 
#gem "sinatra-static-assets", :require_as => "sinatra/static_assets", :git => "git://github.com/lennart/sinatra-static-assets.git"
