# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grammophon}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Varga", "Lennart Melzer"]
  s.date = %q{2010-01-23}
  s.description = %q{A Flex Frontend to KitNo}
  s.email = %q{github@varga-net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
     "lib/grammophon.rb",
     "lib/oggvorbis.swc",
     "script/generate",
     "src/Jukebox.mxml",
     "src/cc/varga/mvc/ApplicationContext.as",
     "src/cc/varga/mvc/ApplicationData.as",
     "src/cc/varga/mvc/service/sound/SoundService.as",
     "src/cc/varga/mvc/views/search/SearchSite.mxml",
     "src/cc/varga/mvc/views/search/SearchSiteEvent.as",
     "src/cc/varga/mvc/views/search/SearchSiteMediator.as",
     "src/com/automatastudios/audio/audiodecoder/AudioDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/AudioInfo.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/IDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/OggVorbisDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/WAVDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/events/AudioDecoderEvent.as",
     "src/com/automatastudios/data/riff/RIFFChunkInfo.as",
     "src/com/automatastudios/data/riff/RIFFParser.as",
     "test/Test-app.xml",
     "test/Test.mxml",
     "views/jukebox.haml"
  ]
  s.homepage = %q{http://github.com/lennart/grammophon/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Flex Frontend to KitNo}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sprout>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<sprout>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<sprout>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

