# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grammophon}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Varga", "Lennart Melzer"]
  s.date = %q{2010-01-06}
  s.description = %q{A Flex Frontend to KitNo}
  s.email = %q{github@varga-net}
  s.files = [
    "Gemfile",
     "lib/grammophon.rb",
     "lib/oggvorbis.swc",
     "script/destroy",
     "script/flex_compile",
     "script/generate",
     "src/FlexPlayer.mxml",
     "src/assets/app_icons/icon_128.png",
     "src/cc/varga/mvc/ApplicationContext.as",
     "src/cc/varga/mvc/commands/data/LoadAlbumsData.as",
     "src/cc/varga/mvc/commands/data/LoadArtistDataCommand.as",
     "src/cc/varga/mvc/commands/playlist/AddItemToPlaylist.as",
     "src/cc/varga/mvc/commands/playlist/LoadPlaylistCommand.as",
     "src/cc/varga/mvc/commands/system/Shutdown.as",
     "src/cc/varga/mvc/commands/system/Startup.as",
     "src/cc/varga/mvc/commands/video/AddVideoCommand.as",
     "src/cc/varga/mvc/events/appBar/AppBarEvent.as",
     "src/cc/varga/mvc/events/blipfm/feedloader/FeedLoaderEvent.as",
     "src/cc/varga/mvc/events/controllers/ControllersEvent.as",
     "src/cc/varga/mvc/events/menu/MenuEvent.as",
     "src/cc/varga/mvc/events/player/PlayerEvent.as",
     "src/cc/varga/mvc/events/playlist/PlaylistEvent.as",
     "src/cc/varga/mvc/events/playlist/PlaylistURLEvent.as",
     "src/cc/varga/mvc/events/playlist/controller/PlaylistControllerEvent.as",
     "src/cc/varga/mvc/events/search/SearchEvent.as",
     "src/cc/varga/mvc/events/serveradmin/ServerAdminEvent.as",
     "src/cc/varga/mvc/events/sound/SoundEvent.as",
     "src/cc/varga/mvc/events/system/SystemEvent.as",
     "src/cc/varga/mvc/models/data/AppDataModel.as",
     "src/cc/varga/mvc/models/player/PlayerModel.as",
     "src/cc/varga/mvc/models/playlist/PlaylistModel.as",
     "src/cc/varga/mvc/models/sound/ISound.as",
     "src/cc/varga/mvc/models/sound/SoundModel.as",
     "src/cc/varga/mvc/models/sound/SoundModelPlayer.as",
     "src/cc/varga/mvc/services/AppMediator.as",
     "src/cc/varga/mvc/views/blipfm/feedloader/FeedLoader.mxml",
     "src/cc/varga/mvc/views/blipfm/feedloader/FeedLoaderMediator.as",
     "src/cc/varga/mvc/views/controllers/Controllers.mxml",
     "src/cc/varga/mvc/views/controllers/ControllersMediator.as",
     "src/cc/varga/mvc/views/infoDisplay/InfoDisplay.mxml",
     "src/cc/varga/mvc/views/infoDisplay/InfoDisplayMediator.as",
     "src/cc/varga/mvc/views/menu/Menu.mxml",
     "src/cc/varga/mvc/views/menu/MenuMediator.as",
     "src/cc/varga/mvc/views/player/PlayerItem.mxml",
     "src/cc/varga/mvc/views/player/PlayerWindow.mxml",
     "src/cc/varga/mvc/views/player/PlayerWindowMediator.as",
     "src/cc/varga/mvc/views/playlist/Playlist.mxml",
     "src/cc/varga/mvc/views/playlist/PlaylistMediator.as",
     "src/cc/varga/mvc/views/playlist/PlaylistStates.as",
     "src/cc/varga/mvc/views/playlistItem/PlaylistItem.mxml",
     "src/cc/varga/mvc/views/playlistItem/PlaylistItemMediator.as",
     "src/cc/varga/mvc/views/playlistManager/PlaylistButton.mxml",
     "src/cc/varga/mvc/views/playlistManager/PlaylistButtonMediator.as",
     "src/cc/varga/mvc/views/playlistManager/PlaylistManager.mxml",
     "src/cc/varga/mvc/views/playlistManager/PlaylistManagerMediator.as",
     "src/cc/varga/mvc/views/playlisturl/PlaylistURL.mxml",
     "src/cc/varga/mvc/views/playlisturl/PlaylistURLMediator.as",
     "src/cc/varga/mvc/views/playlisturl/controller/PlaylistController.mxml",
     "src/cc/varga/mvc/views/playlisturl/controller/PlaylistControllerMediator.as",
     "src/cc/varga/mvc/views/search/Search.mxml",
     "src/cc/varga/mvc/views/search/SearchMediator.as",
     "src/cc/varga/mvc/views/server/administration/ServerAdmin.mxml",
     "src/cc/varga/mvc/views/server/administration/ServerAdminMediator.as",
     "src/cc/varga/mvc/views/visualisation/Visualisation.mxml",
     "src/cc/varga/mvc/views/visualisation/VisualisationMediator.as",
     "src/cc/varga/mvc/views/youtubePlayer/YoutubePlayerContainer.mxml",
     "src/cc/varga/mvc/views/youtubePlayer/YoutubePlayerContainerMediator.as",
     "src/cc/varga/utils/URLHelper.as",
     "src/cc/varga/utils/logging/Logger.as",
     "src/com/automatastudios/audio/audiodecoder/AudioDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/AudioInfo.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/IDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/OggVorbisDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/decoders/WAVDecoder.as",
     "src/com/automatastudios/audio/audiodecoder/events/AudioDecoderEvent.as",
     "src/com/automatastudios/data/riff/RIFFChunkInfo.as",
     "src/com/automatastudios/data/riff/RIFFParser.as",
     "src/grammophon.mxml",
     "src/grammophonRunner.mxml",
     "src/grammophonSkin.css",
     "src/grammophonXMLRunner.mxml",
     "src/libs/appinf/appinf.json",
     "src/libs/appinf/config.json",
     "src/libs/appinf/sample.json",
     "src/libs/appinf/server.json",
     "src/nl/flexcoders/controls/YouTubePlayer.as",
     "test/Test-app.xml",
     "test/Test.mxml",
     "views/jukebox.haml"
  ]
  s.homepage = %q{http://github.com/lennart/grammophon/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Flex Frontend to KitNo}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sprout>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<sprout>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<sprout>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

